name: Docker
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ezrizhu
        password: ${{ secrets.EZRI_CI_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/binpash/hs:${{ github.sha }}
          ghcr.io/binpash/hs:${{ github.ref_name }}

  docker-test-orch:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ezrizhu
        password: ${{ secrets.EZRI_CI_TOKEN }}
    - run: |
        docker run --privileged ghcr.io/binpash/hs:${{ github.sha }} test/test_orch.sh
