name: Run benchmarks

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - aurpkg
          - bio
          - covid-mts
          - file-enc
          - log-analysis
          - max-temp
          - media-conv
          - nlp
          - oneliners
          - riker
          - sklearn
          - unix50
          - vps-audit
          - web-index

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Derive lowercase IMAGE_NAME
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull benchmarks image
        run: |
          docker pull ghcr.io/binpash/benchmarks:latest
          docker tag \
           ghcr.io/binpash/benchmarks:latest \
            benchmark-env

      - name: Set execute permissions for main.sh
        run: chmod +x main.sh

      - name: Run Benchmark ${{ matrix.benchmark }} (min)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/benchmarks \
            -w /benchmarks \
            benchmark-env \
            bash -c "./main.sh ${{ matrix.benchmark }} --bare --min"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.benchmark }}-logs-${{ github.sha }}
          path: ${{ matrix.benchmark }}/${{ matrix.benchmark }}.*
          if-no-files-found: error